# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a26d4f82efd478a98ec0cd452804c61dbe37b9d107f6d039824e596c7492e8a264794992f4489893c0af9126526746959b7de4b98fef304d5c2987d963d2ff54

test:
  secret_key_base: 6dad60ee5f8f7e2f5d904c8ba87b8de71e74fa657ca096b0ed56d9f5d1d7eff4c50072dcec7b3b444da1503778cdd7e18e48e0e34911ad94137a63551a7b4077

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
